<?php


namespace Gremlin\Model;


interface PropertyInterface
{
    function element(): AbstractElement;

    static function empty(): PropertyInterface;

    /**
     * If the property is present, the consume the value as specified by the Consumer.
     *
     * @param Consumer $consumer
     */
    function ifPresent(Consumer $consumer): void;

    /**
     * Whether the property is empty or not.
     */
    function isPresent(): bool;

    /**
     * The key of the property.
     */
    function key(): string;

    /**
     * If the value is present, return the value, else return the provided value.
     *
     * @param mixed $value
     */
    function orElse($value);//: default V;

    /**
     * If the value is present, return the value, else generate a value given the Supplier.
     *
     * @param Supplier $supplier
     */
    function orElseGet(Supplier $supplier);//: default V;

    /**
     * If the value is present, return the value, else throw the exception generated by the Supplier.
     *
     * @param exceptionSupplier $exceptionSupplier
     *
     * @return mixed
     */
    function orElseThrow(exceptionSupplier $exceptionSupplier);//: V;

    /**
     * Remove the property from the associated element.
     */
    function remove(): void;

    /**
     * The value of the property.
     *
     * @return mixed
     */
    function value();

}
